name: Build Flet APK
on: [push] # Mỗi khi bạn thay đổi code, nó sẽ tự build lại

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Flet and Dependencies
        run: |
          pip install flet
          
      - name: Setup Java (Cần để build Android)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Hoặc bản mới nhất

      - name: Build APK
        run: |
          flet build apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my-app-apk
          path: build/apk/*.apk
